import {
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Code,
  Copy,
  Folder,
  Grid3x3,
  Image,
  Lightbulb,
  MessageSquare,
  MoreHorizontal,
  MoreVertical,
  PanelLeft,
  Pencil,
  Plus,
  Radio,
  RefreshCw,
  Search,
  Settings,
  Share,
  Star,
  ThumbsDown,
  ThumbsUp,
  X,
} from "lucide-react";

import { Download, Sparkles } from "../vendor/appsSdkUi";

// Import custom ChatGPT icons for arrow variants
export {
  IconArrowBottomLeftSm,
  IconArrowBottomRightSm,
  IconArrowCurvedLeft,
  IconArrowCurvedRight,
  IconArrowCurvedRightXs,
  IconArrowDownLg,
  IconArrowLeftLg,
  IconArrowRightLg,
  IconArrowRotateCcw,
  IconArrowRotateCw,
  IconArrowTopLeftSm,
  IconArrowTopRightSm,
  IconArrowUpLg,
  IconChevronDownLg,
  IconChevronDownUp,
  IconChevronLeftLg,
  IconChevronRightLg,
  IconChevronUpDown,
  IconChevronUpLg,
  IconCollapseLg,
  IconCollapseSm,
  IconExpandLg,
  IconExpandMd,
  IconExpandSm,
  IconRedo,
  IconRegenerateOff,
  IconRegenerateStar,
  IconReply,
  IconShuffle,
  IconUndo,
} from "../app/components/icons/ChatGPTIcons";

export { Download, Sparkles };

export {
  Archive as IconArchive,
  ArrowLeft as IconArrowLeftSm,
  ArrowRight as IconArrowRightSm,
  ArrowUp as IconArrowUpSm,
  MessageSquare as IconChat,
  CheckCircle as IconCheckCircle,
  Check as IconCheckmark,
  ChevronDown as IconChevronDownMd,
  ChevronLeft as IconChevronLeftMd,
  ChevronRight as IconChevronRightMd,
  ChevronUp as IconChevronUpMd,
  X as IconCloseBold,
  Code as IconCode,
  Copy as IconCopy,
  MoreHorizontal as IconDotsHorizontal,
  MoreVertical as IconDotsVertical,
  Pencil as IconEdit,
  Folder as IconFolder,
  Grid3x3 as IconGrid3x3,
  Image as IconImage,
  Lightbulb as IconLightBulb,
  Plus as IconPlusLg,
  Plus as IconPlusSm,
  Radio as IconRadio,
  RefreshCw as IconRegenerate,
  Search as IconSearch,
  Settings as IconSettings,
  Share as IconShare,
  PanelLeft as IconSidebar,
  Star as IconStar,
  ThumbsDown as IconThumbDown,
  ThumbsUp as IconThumbUp,
  X as IconX,
};
